language: r
r: bioc-release
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
sudo: true
cache:
  packages: true
  directories:
  - "$TRAVIS_BUILD_DIR/_bookdown_files"
env:
  global:
  - secure: TsMaljVdgfcuCbthWTLSNCYRG+TJxpw6XSKYpKTM6/oH1rXv+ygeuSdkPjrrDDA2IqsI6nz4u2C5jc1UthIPm2rpNHqNdkOuRZmLYfiGqtLK0fFDN3r7J/+8ZNpIjeaEQUVKXN+nuUJASpfw7eMXGxl1VjKYgjJilJLdzux0roHUvxi0DfRy0M4aEg+MVXUCsDr8zdo34UVxNYsgFb8Jo/MFmqNRxYGwBkH1+5s7TRW0EDCdFT0HP7z3exhbXO1zf4QzM5MkcdUZYRs1iPyrxKOcBD4Evw0pYf8E7qlVqKwI+6Vku3IUyYl363dQni9XkwkgIWWLOIoIoeCmmtUJjhrBH677PhvfyLB0Yt0XMs7OTjtZooCwzgzpdpG9N1eFN8iSxmRBJHRQU40sZtxLHtJi0Z8/6aLe4G8FoxZcJodxmUeZ67axcFxgRcms/6eeuAwxENMAKEaNZj7NMOXz9Uquzx68q6RNhLqutPcl/XyGCBftFNDoLrqAvETVDgnDakXozqTtFQmswfJxVJ6gtEdO0lmq4uzi17qHr2Ob3iKyFzxTdMh6zIt9bZKiSpMyTwl9D6RcMJ8qhrG0fBrCDCZs4p/OVHKk4toPFHhHOqI29oA08eP36n9y8MgI0nA+Wq9rj/BMcRdiGmnLsOEyvB267e3mCkOWH9WvbAIzBIE=
