# 研究速递

## 十一月 {-}

### 研究动态 {-}

本栏目旨在介绍环境科学、环境工程与生态学及相关学科近期发表的有意思的研究

- 海洋微塑料正在成为研究热点，但密歇根大学的 Allen Burton 却在ES&T上发了篇 Viewpoint 泼冷水，在他眼里，这类研究缺少风险评价，可能毫无意义

推荐人：田振宇

文献链接 http://pubs.acs.org/doi/10.1021/acs.est.7b05463

- 谷歌正在用车载传感器检测街道级别的空气质量

推荐人：于淼

文献链接 http://flowingdata.com/2017/11/08/google-maps-street-level-air-quality-using-street-view-cars-with-sensors/

- 城市热岛效应所引发的温度跟相对湿度变化会影响半挥发化合物的溶解度进而影响pH值，研究人员发现巴尔的摩市跟芝加哥城市跟郊区上空的pH差异在0.8与0.65，当我们讨论区域尺度的大气污染时，城乡差异的来源可能比想象的要复杂

推荐人：于淼

文献链接 http://pubs.acs.org/doi/10.1021/acs.est.7b02786

- 科研作图是很多研究生痛苦的一个根源，然而并不是越炫酷越好，下面这个例子可以说是一个反面教材，过多的立体化、文字化与阴影化处理丢失了图片传达信息的意图，不如直接用表格 （编自 Andrew Gelman的博客） 

推荐人：于淼

链接 https://www.memphisflyer.com/NewsBlog/archives/2016/08/26/report-alcohol-crashes-down-distracted-driving-accidents-up

### 805研究简报 {-}


本栏目旨在介绍805班同学发表的论文

#### 菌根耐铬机理获新进展 - 伍松林 {-}

做为陆地上最为广泛的微生物之一，丛枝菌根（arbuscular mycorrhiza, AM）真菌能与绝大多数的陆地高等植物形成共生体系，帮助植物适应养分贫瘠、干旱、重金属污染等各种逆境胁迫。AM真菌在植物耐受铬污染胁迫中具有重要作用，因而在铬污染土壤生态恢复中具有极大潜在应用价值。然而AM如何促进植物耐受铬污染尚不得而知。

最近一项研究表明AM真菌在六价铬污染情况下能够上调植物根系高亲和硫酸根转运蛋白基因的表达，促进植物根系对硫的吸收。AM真菌同时系统调控了硫在植物体内的转运和代谢以抵御铬污染胁迫。硫代谢产物如半胱氨酸（cysteine, Cys), 谷胱甘肽（glutathione, GSH), 植物络合素（phytochelatins, PCs)等往往能够通过巯基与金属阳离子相结合，进而降低金属毒性。基于此，研究人员推断，AM根系中应有更多的铬与巯基相结合。

然而，事实并非如此，基于同步辐射光源的XAFS分析技术发现，相比较未接种根系，接种AM真菌的根系中有较少的铬与巯基相结合，相反，磷酸结合态铬在AM根系中占主导。这似乎说明，硫代谢产物在菌根耐铬中的作用并不在于络合金属铬。有趣的是，研究人员通过相关分析初步发现，这些主要硫代谢产物（Cys, GSH, PCs）可能在缓解铬引起的植物氧化胁迫中起着重要作用。

相关文章参见：https://www.sciencedirect.com/science/article/pii/S0098847217302939

## 十二月 {-}

### 研究动态 {-}

- 辣木籽被国内保健行业广为吹捧，但它其实是水处理界的明星，将其混合沙子作为滤水器可以去除99%的颗粒物与细菌

推荐人：于淼

链接：http://pubs.acs.org/doi/10.1021/acs.estlett.7b00490

- 这篇等了很久了，USEPA对家用净水器滤芯做的嫌疑物筛选分析和非目标分析。所采用的Brita Filter是美国最常见的家用简易净水器，滤芯里是活性炭和阳离子交换树脂（他们应该给我广告费啊）。饮用水里有哪些污染物？看看这篇文章吧！

非常不错的一个暴露组学范例研究，用非目的分析配合数据库筛选环境水样中的毒性化合物，目测重复难度不大，不过完成这个实验需要多领域专家协作，这篇是EPA外带橡树岭国家实验室配合出来的，国内有同等战力的单位屈指可数

推荐人：田振宇、于淼

链接：https://www.sciencedirect.com/science/article/pii/S026974911732691X

- 把汽车型号，费用，和减排目标联系起来做分析，看看什么车既便宜又环保（可是一般电动车不好修而且开起来太肉啊，well,作者是不是收了Tesla钱了 (●′ω`●)）

推荐人：田振宇

链接：http://pubs.acs.org/doi/10.1021/acs.est.6b00177

- 毒理学研究往往考察单一污染物对单一毒性的影响，EHP上的评论文章引用了一篇双酚类污染物复合暴露的研究指出，针对多污染物与多毒性终点的研究可能给出更多毒理学信息，也需要新的方法学创新

推荐人：于淼

链接：https://ehp.niehs.nih.gov/ehp2341/ https://ehp.niehs.nih.gov/ehp2325

- Environmental DNA (eDNA) 是近些年提出的新概念，指环境样品中可直接测定的非生物来源DNA，可定量分析环境多样性变化，我很好奇这是不是那些搞基因组的发现自己技术过时了就包装下输送到考古跟环境研究领域抢经费了，不过确实是个不错的指标，有希望成为研究热点

推荐人：于淼

链接：http://pubs.acs.org/doi/10.1021/acs.est.7b05199 http://www.sciencedirect.com/science/article/pii/S0006320714004443

- Scripps研究所一直是化学类研究的前沿阵地，脑洞也比较大，在近期提出的一套暴露组学研究流程中研究人员使用了IBM的Watson AI系统来学习文献中的分子并评价暴露组学筛选出的分子，这是要让多少人丢饭碗啊

推荐人：于淼

链接：http://pubs.acs.org/doi/full/10.1021/acs.analchem.7b02759


- “赏金科学家”召集令！！！美国农垦总局出价十万美金征集根除水体中斑马贻贝的方案，欢迎物种入侵相关研究组来美捞金，毕竟一个方案就是两个面上的钱，截止日期二月底

推荐人：于淼

链接：https://www.innocentive.com/ar/workspace/challengeDetail?challenge=9933880


- 来自中国的研究组测了下海盐、湖盐和井盐中的塑料纤维，发现海盐里微塑料明显多于井盐，这个视角比较独特，直接跟食品挂钩了，不过依然缺少风险评价

推荐人：于淼

链接：http://pubs.acs.org/doi/10.1021/acs.est.5b03163


- 这个有点像淼哥之前推荐的 Environmental DNA (eDNA) 那个，不同的是研究者着眼于抗生素抗性基因（antibiotic resistance genes, ARG, 也就是耐药超级细菌所需要的基因）。在污水处理过程中细胞相关的ARG能被较为高效地清除，但是游离的胞外ARG去除效率较低，可能是耐药基因的一个重要来源

推荐人：田振宇

链接：http://pubs.acs.org/doi/10.1021/acs.est.7b04283


- 原来以为原生动物除了难杀灭和能引起奇怪的病之外就没啥意义。然而最近EAWAG的一项研究发现，活性污泥中的原生动物能够通过电荷吸附的作用去除污水中的胺类。

推荐人：田振宇

链接：http://pubs.acs.org/doi/10.1021/acs.est.7b03556

- 五大湖的藻华会影响类似海盐气溶胶的淡水湖气溶胶，单颗粒质谱技术或气溶胶质谱技术有助于我们研究这一特定环境过程，这类概念很不错，但落地还是需要未知物鉴定的数据分析技术，不然还是pca游戏

推荐人：于淼

链接：http://pubs.acs.org/doi/10.1021/acs.est.7b03609


- 拿NHANES数据集发ES&T不新鲜，但搞个10年前的ANN算法来溯源就有点过分了，这种题目放到数据类MOOCs上当作业可能都是送分题，而且数据质量也太差了，0.3%到0.5%的灵敏度还不如随机噪音，没有验证集结果根本就是瞎猜

推荐人：于淼

链接：http://pubs.acs.org/doi/10.1021/acs.est.7b05128

### 805研究简报 {-}


本栏目旨在介绍805班同学发表的论文

#### 氮杂环芳烃环境过程研究新进展 - 田振宇 {-}

氮杂环芳烃（azaarenes）是多环芳烃（PAHs）的氮取代类似物。这类污染物常伴随多环芳烃同时出现在污染场地中，但是由于分析方法的限制，目前对于它们的浓度和环境行为了解十分有限。特别是已知具有较强毒性的高分子量（4-5环）氮杂环芳烃，在各种环境介质的信息都比较缺乏。现有研究大多集中于低分子量（2-3环）的少数几个同类物。换句话说，这类污染物中最危险的东西，我们了解的最少，需要填补这一信息上的空白。

基于高分辨质谱（HRMS）和质量亏损过滤（mass defect filtering），本研究将一种非目标分析方法应用于四个不同污染场地的土壤样品，检测出8个系列共232个同类物。其中四环和五环的氮杂环芳烃被大量检出，种类和浓度都较高。对比污染场地中污染物的分布，可见风化程度高的土壤中四环和五环氮杂环芳烃比例更高。已知有毒且有致癌性的的benzo[c]acridine和dibenzo[a,h]acridine被检出，并且发现它们具有较多的同分异构体。
从本研究可以得出的主要结论是：

- 由于以往的研究忽略了氮杂环芳烃的多样性，它们在污染土壤的毒性中起到的作用很可能被低估；

- 对于土壤中氮杂环芳烃的研究，应更多集中于以往较少关注的高分子量同类物，因为它们的浓度较高且具有持久性。

链接：http://pubs.acs.org/doi/abs/10.1021/acs.est.7b03319
（其实窝是810班的）

## 一月 {-}

### 研究动态 {-}

- ES&T Letter 的执行主编是一个特别喜欢写 editorial 的教授，哪怕一期就三四篇，在 Letter 的 IF 没有超过正刊后，主编大人自己定义了一个 Author Impact Factor（AIF），用过去两年发表数除以2，然后又定义了 L 因子（用 AIF 除以发表期刊的平均 IF ），不得不说这个指标就比较难刷了，有一点他说的非常在理，期刊要以发表的工作为荣，而不是反过来。

推荐人：于淼

链接：http://pubs.acs.org/doi/10.1021/acs.estlett.7b00546

- 用高通量metagenomics 测室内空气中的病毒核酸，采样的地方是12个大学宿舍。宿主多样性很高，而且病毒群落组成可能反映与房间居住者的关联。

推荐人：田振宇

链接：http://pubs.acs.org/doi/10.1021/acs.est.7b04203

- 考虑停留时间，室内空气污染其实比室外影响要大，清华大学的一个研究组考察了中式烹饪过程中室内污染的影响因素，结果发现烹饪方式对大多数污染物影响最严重，基本趋势是炒菜>油炸>蒸煮，如果开了排气扇，大多数污染物浓度都能下降一半。

推荐人：于淼

链接：http://pubs.acs.org/doi/10.1021/acs.est.7b05600

- 左旋葡聚糖经常被用来作为生物质燃烧的标志污染物进行溯源，然而最近的研究发现燃煤也可以生成左旋葡聚糖，这导致我们可能高估了北京的细颗粒物中生物质燃烧的贡献，特别是有燃煤行为的地区

推荐人：于淼

链接：http://pubs.acs.org/doi/10.1021/acs.est.7b05858

- 关于精子质量和大气颗粒物之间关联的流行病学研究。结论比较有意思，说 PM10 (以及与 PM2.5的差) 与精子质量有负相关性，而不是PM2.5。但是大气颗粒物的数据来自区域性的监测和调查问卷，感觉不是很靠谱。

推荐人：田振宇

链接：http://pubs.acs.org/doi/10.1021/acs.est.7b05206

- 光化学反应能在道路尘土中产生单线态氧。大气气相反应和水体光化学反应中的单线态氧并不稀奇，考虑到颗粒物本身就带有各种污染物，这个发现还是有点意思。和持久自由基有无关联？是否会影响stormwater 中的污染物？可以问出一系列的问题了。

推荐人：田振宇

链接：http://pubs.acs.org/doi/10.1021/acs.estlett.7b00533

- 欧盟在2018年又加入了7种严控污染物，有三种含镉物质，另外得克隆也进入名单了，阻燃剂从 PBDEs 开始，几乎就是沿着替代品路线一路禁下去，核心问题在于卤代物天然具有遇热释放卤原子猝灭火焰的特性，替代物都是沿着这个常温稳定，高温分解的思路开发，而这个思路几乎对应持久性有机污染物的特性，这个猫捉老鼠的游戏需要新技术作为搅局者来打破循环。

推荐人：于淼

链接：https://echa.europa.eu/candidate-list-table

- 数据分析方法是长久以来被忽视的研究方向，伴随数据时代的崛起，越来越多的数据人才正在流入传统科研领域掘金，环境学科更是价值洼地，这篇 EHP 的文章是基于 stan 构建的一个贝叶斯在线分析工具，从 stan 角度看就是一个本科生课后作业水平，但 EHP 在环境领域什么份量相信大家都心里有数。总之，不学习新知就会被抛弃，这是学术圈的铁律。

推荐人：于淼

链接：https://ehp.niehs.nih.gov/ehp1289/

## 二月 {-}

### 研究动态 {-}

- 人为设计过的 DNA 被纳米材料包裹后释放到流域中进行溯源是一项非常新的技术，确实 DNA 片段是环境友好的而纳米材料是稳定的，但一个有意思的情况是如果搞 eDNA 研究的跟 DNA-tracer 的都用了一条河… 呃，估计要出大新闻了

推荐人：于淼

链接：http://pubs.acs.org/doi/10.1021/acs.est.7b02928

- 我在逻辑上等这篇文章很久了，就知道微塑料上这个“微”字一定会被“纳”字来入侵，现在果然有人跑出来炒“纳塑料”概念了，一个尺度转换就是一个学科啊

推荐人：于淼

链接：http://pubs.acs.org/doi/10.1021/acs.est.7b05559

- 经济发展对于污染物的迁移等环境过程有着重要影响，这篇研究发现发达地区对周边欠发达地区输送了汞污染或者说优先使用了脱汞技术，这类按经济区域尺度研究的污染不平衡很有意思，如果跟自然地理条件相结合可能会有很有意思的发现

推荐人：于淼

链接：http://pubs.acs.org/doi/10.1021/acs.est.7b04607

- 也是关于微塑料的，用 micro-Raman 检测瓶装水里的微塑料，发现瓶体会向水中直接释放塑料微粒。听起来是有点吓人，浓度呢？真正的风险呢？
推荐人：田振宇
链接：https://www.sciencedirect.com/science/article/pii/S0043135417309272

- 《地球物理学研究快报》发现大约 79.3 ± 46.1 万吨的汞被冻结在永久冻土层中，而 2010 年全球人类活动排放到大气中的汞约为 1960 吨，也就是说，人类直接活动产生的汞也许不算什么，但要是北极的永久冻土层化个30%，现有海洋生态基本要重写了

推荐人：于淼

链接：http://onlinelibrary.wiley.com/doi/10.1002/2017GL075571/full

- 新烟碱类农药是近年来的一个小热点，因为被怀疑导致蜂群崩溃。EST新文章分析了中美的蔬菜水果样品中的7种新烟碱，并和美国农业部农药项目(USDA/PDP)的数据进行了对比，发现中美样品的检出频率都高于USDA的数据。（似乎西红柿的残留更厉害一些?）

推荐人：田振宇

链接：https://pubs.acs.org/doi/10.1021/acs.est.7b05596

- Science上的新研究显示，从挥发性日用化工产品（如杀虫剂、涂料、油墨、清洁剂、个人护理用品等，特别是从室内溢出）排放的VOC已经达到了化石燃料排放量的近一半，逐渐接过了交通运输的份额，并且颇具生成SOA的潜能。（估计以后的法规也会侧重这一块儿）

推荐人：崔天去

链接：http://science.sciencemag.org/content/359/6377/760.full

- Hites 老爷子是为数不多一个人发论文的环境化学科学家，最近他又关注了下 PCB-11，跟传统被禁用的 PCBs 的来源不同，PCB-11 是一种染料生产的副产品，五大湖地区大气中常见 PCBs 的半衰期大概12年，而 PCB-11 在大气中浓度多年来一直稳定，几乎没有半衰期

推荐人：于淼

链接：https://pubs.acs.org/doi/10.1021/acs.estlett.8b00019

- DNA 促进 PAH 在进蒙脱石上的吸附。我们知道一些 PAH 致癌的作用是与DNA 碱基发生不可逆的结合，致使复制出错而突变。反其道而行的话，也可以利用这个机制对PAH 进行吸附。主意不错，但是这么多DNA 哪来？（窝记得窝上中学的实验，DNA 用的是。。。鱼白？）

推荐人：田振宇

链接：https://pubs.acs.org/doi/10.1021/acs.est.7b05174

- Acesulfame K, 中文俗称安赛蜜，是一种难降解的代糖甜味剂，以其稳定性常被用作废水的标志物（去年有人用它计算游泳池里尿的含量）。然额，德国科学家发现它们的废水处理厂中有一些能够较高效地去除这种物质，时间仅用了几年。原因是活性污泥中的某些微生物产生了能够吃掉安赛蜜的能力，真是一种可以观察到的进化。（另一个脑洞，如果肠道微生物也有了这种能力。。。）

推荐人：田振宇

链接：https://pubs.acs.org/doi/10.1021/acs.est.7b05619

- 单萜[Monoterpene]是VOC里的一大自然源，高分辨质谱测到它们贡献了美国东南部（如森林覆盖的阿拉巴马）夏日PM2.5的一半（相当可观），人为排放的NOx也促进了Monoterpene-SOA的生成。（VOC除甲烷外的自然源大概是人为源的10倍，所以其实在很多地方，树是主要问题，而不是车、煤）

推荐人：崔天去

链接：http://www.pnas.org/content/early/2018/02/06/1717513115

## 三月 {-}

### 研究动态 {-}

- 世界范围内只有7%的塑料被循环利用，而亚洲特别是中国基本没有良好的管控，全球90%的海洋微塑料是来自于10条主要河流的输入，其中8条来自亚洲，长江尤为严重

推荐人：于淼

链接：https://www.economist.com/blogs/graphicdetail/2018/03/daily-chart-2

- 三氯生是一种牙膏中常见的杀菌剂，其结构与持久性有机污染物多溴联苯醚及二恶英近似，最近研究发现其在污水处理厂内可转化为甲基三氯生，而甲基三氯生有可以在植物体内转化为三氯生，这类环境转化行为无疑提高了研究其环境过程与环境半衰期的复杂度。

推荐人：于淼

链接：https://pubs.acs.org/doi/10.1021/acs.estlett.8b00071

- 刚看到 Hites 老爷子这篇对 GC-MS 发展历程的前瞻性文章，什么叫老派科学家，老派科学家就是这种看电视上演员把 mass spectrometry 说成 mass spec 后就要跑到 AC 上发文章吐槽的风格，如果你用 GC-MS ，一定看看这篇里对技术发展的梳理，可能很多仪器故障就有思路解决了，不要总是打 800 。

推荐人：于淼

链接：https://pubs.acs.org/doi/abs/10.1021/acs.analchem.6b01628

- 一般认为微生物生物降解处理后的水毒性会降低，但这份研究表明这些代谢产物的毒性并没降低，这个研究比较初步，如果用代谢组学方法研究，可能会揭示更多的毒性细节

推荐人：于淼

链接：https://pubs.acs.org/doi/10.1021/acs.est.7b06408

- 典型外来入侵文章，随机森林算法放在统计学习或机器学习里可能都过时很久了（现在流行各种深度学习、卷积神经网络还有强化学习），但结合环境数据就可以造出一个精度很高的细颗粒物浓度预测模型，以后问题解决型专家可能会比知识型专家更受欢迎，因为有些任督二脉需要合作或通才才能打通

推荐人：于淼

链接：https://pubs.acs.org/doi/10.1021/acs.est.7b05381

- 很有意思的小设备，有点类似温度计，用固相萃取富集，然后用眼睛看颜色扩散长度来决定样品中铜的浓度，原理非常简单，但能组出个能用的产品也是本事，这也是很少有的 ES&T 分析方法类文章

推荐人：于淼

链接：https://pubs.acs.org/doi/10.1021/acs.est.7b05436

- 还记得去年十一月研究速递里说的那个关于海洋微塑料的吐槽吗？现在又有了下文，德国科学家认为，虽然毒性数据短缺，但也不能等着出了问题再亡羊补牢，而合理的解决方法似乎就一个：模型

推荐人：于淼

链接：https://pubs.acs.org/doi/10.1021/acs.est.8b00961

- FT-ICR-MS 研究酒已经是经典案例了，这篇文章更引入了代谢组学的一些方法来研究酒，很难得把故事讲圆了，以后如果再看到品酒专家，可以试探性让他解释下 FT-ICR-MS 是什么。要说跟环境化学的关系，其实酿酒就是个复杂的环境过程，自然界或污水厂都存在类似的场景，同构互换是最简单的发现新研究策略

推荐人：于淼

链接：https://www.frontiersin.org/articles/10.3389/fchem.2018.00029/full

- 石墨烯产品也许还没上市，但环境定量分析已经如火如荼的搞起来了，跟阻燃剂有类似的矛盾，在危害产生前就保持警惕是没问题的，但权衡危害与效益是需要时间来见证的

推荐人：于淼

链接：https://pubs.acs.org/doi/10.1021/acs.est.7b04938