# 研究速递 

## 十一月

### 研究动态

本栏目旨在介绍环境科学、环境工程与生态学及相关学科近期发表的有意思的研究

- 海洋微塑料正在成为研究热点，但密歇根大学的 Allen Burton 却在ES&T上发了篇 Viewpoint 泼冷水，在他眼里，这类研究缺少风险评价，可能毫无意义（田振宇投稿） http://pubs.acs.org/doi/10.1021/acs.est.7b05463 

- 谷歌正在用车载传感器检测街道级别的空气质量（于淼投稿） http://flowingdata.com/2017/11/08/google-maps-street-level-air-quality-using-street-view-cars-with-sensors/ 

- 城市热岛效应所引发的温度跟相对湿度变化会影响半挥发化合物的溶解度进而影响pH值，研究人员发现巴尔的摩市跟芝加哥城市跟郊区上空的pH差异在0.8与0.65，当我们讨论区域尺度的大气污染时，城乡差异的来源可能比想象的要复杂（于淼投稿） http://pubs.acs.org/doi/10.1021/acs.est.7b02786

- 科研作图是很多研究生痛苦的一个根源，然而并不是越炫酷越好，下面这个例子可以说是一个反面教材，过多的立体化、文字化与阴影化处理丢失了图片传达信息的意图，不如直接用表格 （编自 Andrew Gelman的博客） https://www.memphisflyer.com/NewsBlog/archives/2016/08/26/report-alcohol-crashes-down-distracted-driving-accidents-up 

### 805研究简报

本栏目旨在介绍805班同学发表的论文

#### 菌根耐铬机理获新进展 - 伍松林

做为陆地上最为广泛的微生物之一，丛枝菌根（arbuscular mycorrhiza, AM）真菌能与绝大多数的陆地高等植物形成共生体系，帮助植物适应养分贫瘠、干旱、重金属污染等各种逆境胁迫。AM真菌在植物耐受铬污染胁迫中具有重要作用，因而在铬污染土壤生态恢复中具有极大潜在应用价值。然而AM如何促进植物耐受铬污染尚不得而知。最近一项研究表明AM真菌在六价铬污染情况下能够上调植物根系高亲和硫酸根转运蛋白基因的表达，促进植物根系对硫的吸收。AM真菌同时系统调控了硫在植物体内的转运和代谢以抵御铬污染胁迫。硫代谢产物如半胱氨酸（cysteine, Cys), 谷胱甘肽（glutathione, GSH), 植物络合素（phytochelatins, PCs)等往往能够通过巯基与金属阳离子相结合，进而降低金属毒性。基于此，研究人员推断，AM根系中应有更多的铬与巯基相结合。然而，事实并非如此，基于同步辐射光源的XAFS分析技术发现，相比较未接种根系，接种AM真菌的根系中有较少的铬与巯基相结合，相反，磷酸结合态铬在AM根系中占主导。这似乎说明，硫代谢产物在菌根耐铬中的作用并不在于络合金属铬。有趣的是，研究人员通过相关分析初步发现，这些主要硫代谢产物（Cys, GSH, PCs）可能在缓解铬引起的植物氧化胁迫中起着重要作用。相关文章参见：https://www.sciencedirect.com/science/article/pii/S0098847217302939 